mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
	path('', views.index ),
    path('nature/', include('nature.urls')),
    path('admin/', admin.site.urls, name='admin'),
]


nature/urls.py
from django.urls import path

from . import views

app_name = "nature"
urlpatterns = [
    path('', views.index, name='index'),
    path('game', views.game, name='game'),
    path('analytics', views.analytics, name='analytics')
]

nature/models.py
from django.db import models

# Create your models here.

mysite/views.py
# Create your views here.

from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return render(request, 'nature/index.html')

nature/views.py
# Create your views here.

from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return render(request, 'nature/index.html')

def analytics(request):
    return render(request, 'nature/climate_data.html')

def game(request):
    return render(request, 'nature/sample_game.html')


mysite/templates/mysite/base.html
{% load static %}
<html>
  <head>
  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">

    <title>Climate Solutions</title>

    <!-- Bootstrap + CSS -->
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/navbar-static/">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">

    <!-- Custom CSS/styles for this template -->
    <link href="{% static 'nature/css/carousel.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'nature/css/navbar-top.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'nature/css/game_style.css' %}" rel="stylesheet" type="text/css"></link>
    <link href="{% static 'nature/css/common_design.css' %}" rel="stylesheet" type="text/css"></link>
    <link href="{% static 'nature/css/custom-2.css' %}" rel="stylesheet" type="text/css"></link>

     <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <!-- Javascript  -->
    <script src="{% static 'nature/src/base.js' %}" type="text/javascript"></script>

    
    <!-- React.js -->
    <script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>

    <!-- Other Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.2/dist/chart.umd.js" 
            integrity="sha384-eI7PSr3L1XLISH8JdDII5YN/njoSsxfbrkCTnJrzXt+ENP5MOVBxD+l6sEG4zoLp" 
            crossorigin="anonymous"></script>

  </head>

  <body>
    <header class="moved-up">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 small-bottom">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Finding Solutions</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a id="nav-home" class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            {% comment %}
            <li class="nav-item">
              <a id="nav-2" class="nav-link" href="{% url 'nature:analytics' %}">Analytics</a>
            </li>
            {% endcomment %}
            <!-- <li class="nav-item">
              <a class="nav-link" href="game">Interactive</a>
            </li> -->

            <!-- <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li> -->
          </ul>
          <!-- <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form> -->
        </div>
      </div>
    </nav>
    </header>
    
    <!-- <img src="{% static 'images/sitelogo.png' %}" alt="Logo"> -->
    {% block content %}{% endblock %}

    <footer class="pt-3 mt-4 text-muted border-top left-padding-footer">
      &copy; <span id="current_year"></span> Rahul Birla
    </footer>

    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
             crossorigin="anonymous"> 
    </script>

    <!-- <script src="{% static 'nature/src/climate-dashboard.js' %}" type="text/javascript"></script> -->
    
  </body>
</html>

nature/templates/nature/index.html
{% extends "mysite/base.html" %}
{% load static %}


{% block content %}
    <main>
      <div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>

        <div class="carousel-inner">
          <div class="carousel-item active">
            <!-- <svg class="bd-placeholder-img" width="100%" height="100%" 
             xmlns="http://www.w3.org/2000/svg"
            aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"></svg> -->
            <img src="{% static 'nature/img/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass.jpg' %}" alt="wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass" width="1000" height="600" type="image/jpeg" class="responsive" 
            style="opacity: 87%;">


            <div class="container">
              <div class="carousel-caption text-start">
                <h1>Living in a Sustainable Manner</h1>
                <a href="https://www.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_11342065.htm#query=nature&position=0&from_view=keyword&track=sph" class="link-color-black">Image by wirestock</a> on Freepik
                <!-- <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p> -->
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static 'nature/img/ian-parker-ihByWVBKIPY-unsplash.jpg' %}" 
                alt="Penguins" width="1000" height="600" type="image/jpeg" class="responsive light-image" >
            <div class="container">
              <div class="carousel-caption">
                <h1 class="dark-colour">Help Sustain Biodiversity</h1>
                <p class='dark-colour'> Photo by <a href="https://unsplash.com/@evanescentlight?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" class="link-color-blue">Ian Parker</a> on <a href="https://unsplash.com/photos/ihByWVBKIPY?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" class="link-color-blue">Unsplash</a></p>
              </div>
            </div>
          </div>

          <div class="carousel-item">
            <img src="{% static 'nature/img/beautiful-nature-scenery-picjumbo-com.jpg' %}" alt="Valley" width="1000" height="600" type="image/jpeg" class="responsive" >

            <div class="container">
              <div class="carousel-caption text-end">
                <h1>Live a Clean and Healthy Life</h1>
                <p> Photo by <a href="https://picjumbo.com/author/viktorhanacek/" class="link-color-grey">Victor Hanacek</a></p>
              </div>
            </div>
          </div>
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>

      </div>


      <div class="container">
        <div class="bg-light p-5 rounded">

          <div class="row">
            <div class="col-md-12">
              <div class="p-5 mb-4 bg-light rounded-3">
                <div class="container-fluid py-5">
                  <h1 class="display-5 fw-bold">Moving Forward towards the Future</h1>
                    <div class="row">
                      <div class="col-md-12">

                       <p class=" fs-4">There are many ways to help the earth, in a sustainable manner. You can make a difference.</p>
                       <br>

                       <p>The Paris Agreement was made by countries to help battle the effects of climate change.
                       Countries, as part of the agreement, aim to be net-zero in their carbon footprint by the year 2050. This is
                       to reduce the earth warming by more than 1.5 degrees Celsius. Scientists say that a 2 degrees celsius increase will
                       lead to irreparable issues on earth, so the agreement aims to get all the countries in the world to aim for net-zero 
                       emissions to avoid these catastrophic issues. The aim of this site is to provide information on environmental issues, while also presenting information about the economy, so that sustainable solutions can be found, that work for everyone, in the best way forward.</p>


                       <img src="{% static 'nature/img/MtFuji.jpg' %}" alt="Mount Fuji" width="1000" height="600" type="image/jpeg" class="responsive image-mount-fuji-light">
                       <br>
                     </div>
                   </div>
                  
                </div>
              </div>
            </div>
          </div>

          <div class="row align-items-md-stretch">
            <div class="col-md-6">
              <div class="h-100 p-5 text-white bg-dark rounded-3">
                <p class="lead">Take small steps in your life. Each step matters.</p>

                <h2> Ways to help</h2>
                <ol>
                  <li>Plant a tree</li>
                  <li>Reduce, Reuse, Recycle</li>
                  <li>Learn more about environmental issues</li>
                  <li>Spread the word to others</li>
                </ol>
              </div>
            </div>
            <div class="col-md-6">
              <div class="h-100 p-5 bg-light border rounded-3">
                <h2>Some organizations that are making a change</h2>
                <ul>
                  <li><a href="https://davidsuzuki.org/" target="_blank">David Suzuki Foundation</a></li>
                  <li><a href="https://fridaysforfuture.org/" target="_blank">Fridays For Future</a></li>
                </ul>
                
              </div>
               
            </div>

          </div>


          <div class="row">
            <div class="col-md-12">
              <div class="p-5 mb-4 bg-light rounded-3">
                <div class="container-fluid py-5">

                  <h2> Information on the Paris Agreement</h2>

                  <p> Countries are aiming to reduce carbon emissions to net-zero, by the year 2050. 
                      Immediate action is needed. Here is some more information.</p>
                  <ul>
                    <li><a href="https://unfccc.int/process-and-meetings/the-paris-agreement/the-paris-agreement" 
                      target="_blank">Info on Paris Agreement</a></li>
                  </ul>
                 
                  <br>
                 <!--  <button class="btn btn-primary" role="button">Hello</button> -->

                </div>
              </div>
            </div>
          </div>

          <!-- <div class="row">
            <div class="col-md-12">
              <h3>Current Disasters Around the World</h3>
              <br>
              <p>Here are some issues happening around the world:</p>
              <ul>
                <li id="disaster_events_1"></li>
                <li id="disaster_events_2"></li>
                <li id="disaster_events_3"></li>
                <li id="disaster_events_4"></li>
                <li id="disaster_events_5"></li>
              </ul>
              
            </div>
            <a href="https://reliefweb.int/disasters" target="_blank">More specific info on Disasters</a>
          </div> -->

          
        </div>

      </div>
    </main>
   
{% endblock %}

nature/templates/nature/sample_game.html
{% extends "mysite/base.html" %}
{% load static %}


{% block content %}

<!-- 
<head>
    <meta charset="utf-8" />
    <title>Gamedev Canvas Workshop</title>
    
</head> -->

<!-- <body> -->
  <h1 style="margin-left:25px;">Game</h1>

  <button onclick="startGame()" class='game-btn btn-primary'>Start</button>
  <button onclick="stopGame()" class='game-btn btn-primary'>Pause</button> 
  <button onclick="moveUp()" class='game-btn btn-primary'>Up</button>
  <button onclick="moveDown()" class='game-btn btn-primary'>Down</button>

  <canvas id="canvas"></canvas>

 

<script>

    // window.addEventListener('Arrowdown', function (e) {
    //     //document.querySelector('p').innerHTML = `You pressed ${e.key}`;
    //     changeColour();
    // }, false);

    function showEnvData(data) {
      console.log(data)
      events_array = data.data;
      all_events = [];

      for (var i = 0; i <= events_array.length - 1; i++) {
        console.log(events_array[i]);
        title = events_array[i].fields.title;
        all_events.push(title)
      }

      console.log(all_events)


    }

    fetch('https://api.reliefweb.int/v1/reports?appname=apidoc&limit=2')
      .then((response) => response.json())
      .then((data) => showEnvData(data));

    

    function startGame() {
        myGameArea.start();
    }

    function stopGame() {
        clearInterval(myGameArea.interval);
    }
  
    var myGameArea = {
        canvas : document.getElementById("canvas"),
        start : function() {
          // clear previous intervals
          if (this.interval){
            clearInterval(this.interval);
          }
          this.canvas.width = 480;
          this.canvas.height = 270;
          this.context = this.canvas.getContext("2d");
          //document.body.insertBefore(this.canvas, document.body.childNodes[0]);
          //this.interval = setInterval(draw, 10);
          draw();
          
        }
    }

    // intialization
    var x = myGameArea.canvas.width/2;
    var y = myGameArea.canvas.height-30;
    var dx = 2;
    var dy = -2;
    var ballRadius = 10;
    var colour = "#0095DD";
    
    function drawBall() {
      myGameArea.context.beginPath();
      myGameArea.context.arc(x, y, ballRadius, 0, Math.PI*2);
      myGameArea.context.fillStyle = colour;
      myGameArea.context.fill();
      myGameArea.context.closePath();
   }

    function changeColour(){
      colours = []
      if (colour == "#0095DD"){
          colour = "#633ac5";
      }else {
          colour = "#0095DD";
      }
    }


  
    function draw() {
      // drawing code
      myGameArea.context.clearRect(0, 0, myGameArea.canvas.width, myGameArea.canvas.height);
   
      drawBall();

      if(x + dx > myGameArea.canvas.width-ballRadius || x + dx < ballRadius) {
          dx = -dx;
          changeColour();
        }

      if(y + dy > myGameArea.canvas.height-ballRadius || y + dy < ballRadius) {
          dy = -dy;
          changeColour();
      }

      x += dx;
      y += dy;
    }

    function moveUp() {
      // drawing code
      myGameArea.context.clearRect(0, 0, myGameArea.canvas.width, myGameArea.canvas.height);
   
      drawBall();

      dy = -5;
      dx = 0;


      if((x + dx > myGameArea.canvas.width-ballRadius) || (x + dx < ballRadius)) {
          dx = -dx;
          //changeColour();
        }

      if((y + dy > myGameArea.canvas.height-ballRadius) || (y + dy < ballRadius)) {
          dy = 0;
          //changeColour();
      }

      x += dx;
      y += dy;
    }

    function moveDown() {
      // drawing code
      myGameArea.context.clearRect(0, 0, myGameArea.canvas.width, myGameArea.canvas.height);
   
      drawBall();

      dy = 5;
      dx = 0;


      if((x + dx > myGameArea.canvas.width-ballRadius) || (x + dx < ballRadius)) {
          dx = -dx;
          //changeColour();
        }

      if((y + dy > myGameArea.canvas.height-ballRadius) || (y + dy < ballRadius)) {
          dy = 0;
          //changeColour();
      }

      x += dx;
      y += dy;
    }

</script>

{% endblock %}